// Copyright (c) 2025 Arye Gross
// SPDX-License-Identifier: Apache-2.0

#include <assert.h>

#ifdef CP_USE_USER_CONFIG
#include "cmsisPosix_UserConfig.h"
#endif

#define CP_CONFIG_SCHEDULING_NICE 0
#define CP_CONFIG_SCHEDULING_ROUND_ROBIN 1
#define CP_CONFIG_SCHEDULING_FIFO 2

#ifndef CP_CONFIG_SCHEDULING
#define CP_CONFIG_SCHEDULING CP_CONFIG_SCHEDULING_ROUND_ROBIN
#endif

#if CP_CONFIG_SCHEDULING == CP_CONFIG_SCHEDULING_NICE
#define CP_SCHED SCHED_OTHER
#elif CP_CONFIG_SCHEDULING == CP_CONFIG_SCHEDULING_ROUND_ROBIN
#define CP_SCHED SCHED_RR
#elif CP_CONFIG_SCHEDULING == CP_CONFIG_SCHEDULING_FIFO
#define CP_SCHED SCHED_FIFO
#else
#error CP_CONFIG_SCHEDULING not defined (or defined with bad value)
#endif

#ifndef CP_CONFIG_NANO_IN_TICK
#define CP_CONFIG_NANO_IN_TICK 1000000L // 1 mSec
#endif
